---
title: "Data management & IRB"
subtitle: "710 | Week 3"
author: "Bradley McDonnell"
date: "2020/9/10 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: center, middle

# Data management discussion

## Thieberger & Berez (2012), Cox (to appear) 

---

# Data management activity

1. Based upon the information your group has been given, create a data management workflow. In so doing, answer the following questions: 

  - How will you collect data? 
  - In what forms will it be recorded?
  - How/when will you process the data?
  - What software will you use?
  - How will you manage metadata? 
  - ...

***Provide a practical and specific plan with an appropriate workflow based upon what you learned from Thieberger & Berez (2012) and Cox (to appear).***

---
class: center, middle

# Metadata discussion

## Good (2011), Bowern (2015)

---
class: center, middle
# Metadata heirarchy


## Project

### Corpus

#### Session

##### Resource

---

# Organizing metadata

We'll consider two ways of organizing metadata. 
  
  1. Spreadsheet [Kaipuleohone](../2021-710/slides-handouts/3-metadata-archiving/kaipuleohone-depositor-metadata.xls)
  2. Database 
    - [lameta](https://github.com/onset/lameta/releases) for Mac, PC 
    - [SayMore](https://software.sil.org/saymore/) for PC

Let's take a quick tour of **lameta**


---
class: center, middle

# IRB discussion

## DiPersio (2014)


---

# What is an IRB?

<iframe width="560" height="315" src="https://www.youtube.com/embed/d15kYGwYU24?start=7" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

---

# IRB at UH

- The UH Human Studies Program is under the Office of Research Compliance: <https://researchcompliance.hawaii.edu/programs/human-studies/>

- Information on submitting a protocol can be found:  <https://researchcompliance.hawaii.edu/programs/human-studies/uh-eprotocol/>

- Protocols are submitted on **eprotocol**: <https://uhmanoa.keyusa.net/>

- CITI info can be found under training: <https://researchcompliance.hawaii.edu/programs/human-studies/hs-training/>
